// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkkkszmqorbdgzxfzgsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra2tzem1xb3JiZGd6eGZ6Z3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzEyMzMsImV4cCI6MjA2NTU0NzIzM30.tiAroYeBr0YXXspOqaWjblW8XAwrdZBQSV7czKSuH0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);